# Generated by Django 3.2.4 on 2021-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210621_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
